### ISSUE TITLE
Rewrite project structure so that goquery can be imported as a library

### ISSUE THREAD

**Issue by AbGuthrie** [AbGuthrie/goquery#110]
As of @directionless's suggestion, it makes more sense for goquery to be imported as a library, rather than needing to clone and modify the source to get any integration working.

`main.go` should be reworked so that the entry point is in goquery.go with a call to Start(api GoQueryAPI, config Config) where api is either a custom or referenced built in API and config is a populated Config struct.

An example wrapper `example.go` can be used to demonstrate integration, and also used to `go run` to see an example working quickly.

**Comment by AbGuthrie** [comment]
In addition, goquery does not need to be responsible for command line argument parsing. Since there will be an outer wrapper go file handling the call and options configured for goquery, the responsibility is of the caller to configure the options.

**Comment by zwass** [comment]
@AbGuthrie Do you expect to do refactoring to the API for working with a server? We are looking at implementing for Fleet and wondering whether we should wait for this refactor.

**Comment by AbGuthrie** [comment]
Hi Zachary, integration revolves around the [GoQueryAPI interface](https://github.com/AbGuthrie/goquery/blob/master/api/models/models.go#L11). I will be aiming to keep it as stable as possible. 
With the current implementation, users would need to git clone and then create a new file within the `api` folder. This is obviously not ideal.

This ticket's effort will not change API interface, but will change where the custom APIcode lives and how its passed in. It would make more sense for users to just import goquery and pass their custom GoQueryAPI object to the main function.

It would be a good idea to wait because you wont need to git clone and build manually to integrate!
